codes/mysite/datasetviewer/urls.py
from django.urls import path

from . import views

app_name = 'datasetviewer'
urlpatterns = [
    # ex: /datasetviewer/
    path('', views.index, name='index'),
    # ex: /datasetviewer/1/original_dataset/
    path('<int:show_landmark>/<dataset_name>/', views.overview, name='overview'),
    # ex: /datasetviewer/1/original_dataset/Xiang_Liu/
    path('<int:show_landmark>/<dataset_name>/<people_name>/', views.detail, name='detail'),
    # ex: /datasetviewer/1/original_dataset/Xiang_Liu/C00001
    path('<int:show_landmark>/<dataset_name>/<people_name>/<image_name>', views.view_image, name='view_image'),
    # ex: /datasetviewer/pose/original_dataset/Xiang_Liu/C00001
    path('pose/<dataset_name>/<people_name>/<image_name>', views.view_pose, name='view_pose'),
]

codes/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('datasetviewer/', include('datasetviewer.urls')),
    path('stylized_face/', include('stylized_face.urls')),
    path('admin/', admin.site.urls),
]

codes/mysite/stylized_face/urls.py
from django.urls import path

from . import views

app_name = 'stylized_face'
urlpatterns = [
    # ex: /stylized_face/
    path('', views.upload, name='index'),
    # ex: /stylized_face/p2c_overview/file_name.jpg/
    path('p2c_overview/<img_name>/', views.overview, name='p2c_overview'),
    # ex: /stylized_face/file_name.jpg
    path('<img_name>/', views.detail, name='detail')
]

codes/mysite/datasetviewer/models.py
from django.db import models

# Create your models here.

codes/mysite/stylized_face/models.py
from django.db import models

# Create your models here.

codes/mysite/datasetviewer/views.py
import os

from django.http import HttpResponse
from django.shortcuts import render

from . import config
from .datas import get_dirs, get_image, get_overview, get_pose, get_missing_file
from .utils import dict_to_str

# Create your views here.
def return_an_error_page_if_DirNotFindError(func):
    def warpper(*args, **kw):
        try:
            return func(*args, **kw)
        except config.DirNotFindError as e:
            request = kw['request'] if 'request' in kw else args[0]
            return render(request, 'datasetviewer/error.html', {
                'error_message': e.args[0],
            })
    return warpper


def index(request):
    datasets = os.listdir(config.WC_datasets_dir)
    return render(request, 'datasetviewer/index.html', {'datasets': datasets})


@return_an_error_page_if_DirNotFindError
def overview(request, dataset_name, show_landmark=1):
    (images_dir, filenames_dir, landmarks_dir), messages = get_dirs(dataset_name)

    people_names, image_names, landmarks = get_overview(images_dir, filenames_dir, landmarks_dir)
    missing_file = get_missing_file(dataset_name)
    missing_file = dict_to_str(missing_file)

    return render(request, 'datasetviewer/overview.html', {
        'messages': messages,
        'dataset_name': dataset_name,
        'people_names_and_image_names': [(people_name, image_names[people_name]) for people_name in people_names],
        'show_landmark': show_landmark,
        'total_people': len(people_names),
        'total_images': sum(map(len, landmarks.values())),
        'missing_file': missing_file,
    })


@return_an_error_page_if_DirNotFindError
def detail(request, dataset_name, people_name, show_landmark=1):
    (images_dir, filenames_dir, landmarks_dir), messages = get_dirs(dataset_name)

    people_names, image_names, landmarks = get_overview(images_dir, filenames_dir, landmarks_dir)

    return render(request, 'datasetviewer/detail.html', {
        'messages': messages,
        'dataset_name': dataset_name,
        'people_name': people_name,
        'show_landmark': show_landmark,
        'image_names': image_names[people_name],
    })


@return_an_error_page_if_DirNotFindError
def view_image(request, dataset_name, people_name, image_name, show_landmark=1):
    image = get_image(dataset_name, people_name, image_name, show_landmark)

    return HttpResponse(image, content_type="image/jpg")


@return_an_error_page_if_DirNotFindError
def view_pose(request, dataset_name, people_name, image_name):
    # TODO: add expicit url to this view
    pose = get_pose(dataset_name, people_name, image_name)
    return HttpResponse(', '.join(map(str, map(int, pose))))


if __name__ == '__main__':
    overview(None, config.WC_original_dataset_name)

codes/mysite/stylized_face/views.py
import os
import time

import numpy as np
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response, reverse
from PIL import Image

from .stylize import alignment, stylize

path = os.path.join('support_material', 'stylizer')


def IsValidImage(img_path):
    bValid = True
    try:
        Image.open(img_path).verify()
    except:
        bValid = False
    return bValid


# Create your views here.
def handle_upload_file(file, filename):
    if not os.path.exists(path):
        os.makedirs(path)
    file_path = os.path.join(path, filename)
    with open(file_path,'wb') as destination:
        for chunk in file.chunks():
            destination.write(chunk)
    if not IsValidImage(file_path):
        return None
    file_path_split = os.path.splitext(file_path)
    if file_path_split[1] != '.jpg':
        img = Image.open(file_path)
        file_path = file_path_split[0] + '.jpg'
        img.save(file_path)
    return file_path


def upload(request):
    if request.method=="POST":
        filenames = os.path.splitext(str(request.FILES['file']))
        filename = time.strftime('%Y-%m-%d-%H-%M-%S', time.localtime())+str(np.random.randint(800820))+filenames[1]
        raw_file_path = handle_upload_file(request.FILES['file'], filename)
        if raw_file_path is None:
            return render_to_response('stylized_face/index.html')
        align_file_path = alignment(raw_file_path)
        align_file_name = os.path.split(align_file_path)[1]
        return HttpResponseRedirect(reverse('stylized_face:p2c_overview', args=(align_file_name,)))
 
    return render_to_response('stylized_face/index.html')


def overview(request, img_name):
    seed = np.random.randint(800820)
    img_path = os.path.join(path, img_name)
    sty_path = stylize(img_path, seed)
    sty_name = os.path.split(sty_path)[1]
    return render(request, 'stylized_face/p2c_overview.html', {
        'img_name': img_name,
        'sty_name': sty_name,
    })


def detail(request, img_name):
    img_path = os.path.join(path, img_name)
    image = open(img_path, 'rb').read()
    return HttpResponse(image, content_type="image/jpg")

codes/mysite/datasetviewer/templates/datasetviewer/detail.html
{% include 'datasetviewer/header.html' %}

{% for message in messages %}
    {% if message %} <p>{{ message }}</p> {% endif %}
{% endfor %}

<a href="{% url 'datasetviewer:detail' 0 dataset_name people_name %}">disable landmark</a><br>
<a href="{% url 'datasetviewer:detail' 1 dataset_name people_name %}">enable landmark</a><br>
<br>

<style>
    *{
        margin: 0;
        padding: 0;
    }
.red{
    width: 100%;
    height: 30px;
    border: 1px solid red;
}
.blue{
    width: 100%;
    height: 30px;
    border: 1px solid blue;
}
.clearfix:after{
    position: relative;
    content: '';
    display: block;
    width: 0;
    height: 0;
    visibility: hidden;
    clear: both;
}
li {
    list-style: none;
    float: left;
    width: 20%;
    height: 256px;/*当图片尺寸不一的时候，设置一个高度*/
    overflow: hidden;/*超出隐藏*/
}
li img {
    position: relative;
    width: 100%;
    top: 100%;
    transform: translateY(-100%);
}
.clearfix:after {
  visibility: hidden;
  display: block;
  font-size: 0;
  content: " ";
  clear: both;
  height: 0;
}
.container{
    width: 60%;
    margin: 0 auto;
}
</style>

<p><strong>{{ people_name }}</strong></p>
<div class="container"> 
    <p>caricatures</p><br>
    <ul class="clearfix"> 
        {% for image_name in image_names.c %}
        <li>
            <a href="{% url 'datasetviewer:view_image' show_landmark dataset_name people_name image_name %}" target="_blank">
                <img src="{% url 'datasetviewer:view_image' show_landmark dataset_name people_name image_name %}">
            </a>
        </li>    
        {% endfor %}
    </ul>
</div>
<div class="container"> 
    <p>photos</p><br>
    <ul class="clearfix"> 
        {% for image_name in image_names.p %}
        <li>
            <a href="{% url 'datasetviewer:view_image' show_landmark dataset_name people_name image_name %}" target="_blank">
                <img src="{% url 'datasetviewer:view_image' show_landmark dataset_name people_name image_name %}">
            </a>
        </li>    
        {% endfor %}
    </ul>
</div>

codes/mysite/datasetviewer/templates/datasetviewer/error.html
{% include 'datasetviewer/header.html' %}

<strong><p>{{ error_message }}</p></strong>

codes/mysite/datasetviewer/templates/datasetviewer/header.html
<h1>DatasetViewer</h1>
written by <a href="http://yujiachen.top/">Jiachen Yu</a><br>

codes/mysite/datasetviewer/templates/datasetviewer/index.html
{% include 'datasetviewer/header.html' %}

<ul>
{% for dataset_name in datasets %}
    <li><a href="{% url 'datasetviewer:overview' 1 dataset_name %}">{{ dataset_name }}</a></li>
{% endfor %}
</ul>

codes/mysite/datasetviewer/templates/datasetviewer/overview.html
{% include 'datasetviewer/header.html' %}

{% for message in messages %}
    {% if message %} <br><p>{{ message }}</p><br> {% endif %}
{% endfor %}

<a href="{% url 'datasetviewer:overview' 0 dataset_name %}">disable landmark</a><br>
<a href="{% url 'datasetviewer:overview' 1 dataset_name %}">enable landmark</a><br>
<br>

<strong><p>
    there are {{total_images}} images from {{total_people}} people.
</p></strong>

<strong><p>
    missing file in Evaluation Protocols
</p></strong>
<p><pre>{{missing_file}}</pre></p>
<br>

<style>
    *{
        margin: 0;
        padding: 0;
    }
.red{
    width: 100%;
    height: 30px;
    border: 1px solid red;
}
.blue{
    width: 100%;
    height: 30px;
    border: 1px solid blue;
}
.clearfix:after{
    position: relative;
    content: '';
    display: block;
    width: 0;
    height: 0;
    visibility: hidden;
    clear: both;
}
li {
    list-style: none;
    float: left;
    width: 10%;/*三列图片排列*/
    height: 128px;/*当图片尺寸不一的时候，设置一个高度*/
    overflow: hidden;/*超出隐藏*/
}
li img {
    position: relative;
    width: 100%;
    top: 50%;/*li高度的一半*/
    transform: translateY(-50%);
}
.clearfix:after {
  visibility: hidden;
  display: block;
  font-size: 0;
  content: " ";
  clear: both;
  height: 0;
}
.container{
    width: 60%;
    margin: 0 auto;
}
</style>

{% for people_name, image_names in people_names_and_image_names %}
    <!-- <div style="float:left; clear:both;"> -->
        <a href="{% url 'datasetviewer:detail' show_landmark dataset_name people_name %}">{{ people_name }}</a>
        <div class="container"> 
            <ul class="clearfix">
                {% for image_name in image_names.c %}
                <li>
                    <a href="{% url 'datasetviewer:view_image' show_landmark dataset_name people_name image_name %}" target="_blank">
                        <img src="{% url 'datasetviewer:view_image' show_landmark dataset_name people_name image_name %}">
                    </a>
                </li>    
                {% endfor %}
            </ul>
        </div>
        <div class="container"> 
            <ul class="clearfix"> 
                {% for image_name in image_names.p %}
                <li>
                    <a href="{% url 'datasetviewer:view_image' show_landmark dataset_name people_name image_name %}" target="_blank">
                        <img src="{% url 'datasetviewer:view_image' show_landmark dataset_name people_name image_name %}">
                    </a>
                </li>    
                {% endfor %}
            </ul>
        </div>
    <!-- </div> -->
{% endfor %}

codes/mysite/stylized_face/templates/stylized_face/index.html
上传一张有人脸的图片吧
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form class="form-inline" role="form"  method="post" enctype="multipart/form-data" accept-charset="utf-8">
            <div class="form-group">
                <input type="file" name="file">
            </div>
            <div class="form-group">
                <input type="submit" value="上传文件">
            </div>
        </form>
    </div>
</div>

codes/mysite/stylized_face/templates/stylized_face/p2c_overview.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>照片转画像</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <img src="{% url 'stylized_face:detail' img_name %}">
    <img src="{% url 'stylized_face:detail' sty_name %}">    
    <button id="reload">换个样式</button>
    <script>
        document.querySelector('#reload').addEventListener('click',function(){
            window.location.reload()
        })
    </script>
</body>
</html>